### ISSUE TITLE
Can not use `amazon:~` tags.

### ISSUE THREAD

**Issue by hideokamoto** [jubilee-works/ssml-tsx#40]
Hi!
Thanks for publishing a cool library!.

I try to use it for my Alexa Skill, but I found the following issue.

## Expect
Render to string my SSML using `amazon:XXX` tag.

**Example**
```tsx
<speak>
      <amazon:effect name="whispered">effect</amazon:effect>
      <amazon:emotion name="excited" intensity="low">emotion</amazon:emotion>
      <amazon:domain name="news">domain</amazon:domain>
      </speak>
```

## Actual
TypeScript throw Error.

![スクリーンショット 2020-04-09 23 42 07](https://user-images.githubusercontent.com/6883571/78907583-dc32a100-7abb-11ea-8409-12ca364b4475.png)

## Problem
Probably, we can not use JSX/TSX element using `:`.

## Solution
We have to convert these component name and re-convert to a valid name.

**Comment by fujikky** [comment]
Fixed in #41 and released as v1.0.9
https://github.com/jubilee-works/ssml-tsx/releases/tag/v1.0.9
